default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: .venv/bin/python tools/run_black_hook.py
        language: system
        types_or:
          - python
        require_serial: true
      - id: mypy
        name: mypy
        entry: .venv/bin/mypy
        language: system
        types_or:
          - python
        require_serial: true
      - id: conventional-pre-commit
        name: conventional-pre-commit
        entry: .venv/bin/conventional-pre-commit
        language: system
        stages:
          - commit-msg
        args: [fix, feat, chore, docs, style, refactor, perf, test, revert, ci, build]
